import Link from "next/link";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <nav className="flex flex-row gap-10 h-15">
          <h2>Humber</h2>
          <nav className="flex gap-10">
            <Link href={'/books'}>books</Link>
            <Link href={'/add-book'}>add book</Link>
          </nav>
        </nav>
        {children}
      </body>
    </html>
  );
}
