import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";


// sets up our fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
// sets up our fonts
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// sets up our metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// this is our actual component!
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav>
            <Link href={`/dogs`}>dogs</Link>
            <Link href={`/about-us`}>About</Link>
          </nav>
        </header>
        <h2>THis renders on every single page!</h2>
        {/* children is a placeholder - whatever page.js should be renedered goes here (based on the route) */}
        {children}
      </body>
    </html>
  );
}
