import "./globals.css";
import { ClerkProvider, SignedOut, SignedIn, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
      
        <body className={`antialiased`}>
          <div>
            {/* Anything indie the SignedOut component will only display when the user is signed out */}
            <SignedOut>
              <h2>Hello!</h2>
              {/* if the user is not signed in, we show them these buttons */}
              <SignInButton/>
              <SignUpButton />
            </SignedOut>
            {/* So anything inside the SignedIn component will only display when the user is signed in */}
            <SignedIn>
              <p>Goodbye!</p>
              <UserButton />
            </SignedIn>
          </div>
          {children}
          </body>
      </html>
    </ClerkProvider>
  );
}
