import { Sour_Gummy, Libre_Barcode_39, Honk} from "next/font/google";
import "./globals.css";

const sourGummy = Sour_Gummy({
  subsets: ['latin']
})

export const libreBarcode = Libre_Barcode_39({
  weight: '400'
})

export const honk = Honk({
  variable: '--font-honk'
})

export const metadata = {
  title: "Quote app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log(sourGummy)
  return (
    <html lang="en">
      <body
        className={`${sourGummy.className} ${honk.variable} antialiased`}
        style={{height: '100vh'}}
        // style={{height: '100vh', ...sourGummy.style}}
      >
        {children}
      </body>
    </html>
  );
}
